# Generated by Django 5.1.5 on 2025-02-06 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetingroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aganda',
            new_name='Agenda',
        ),
    ]
