# Generated by Django 5.1.5 on 2025-02-03 07:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectparticipation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='projectparticipation',
            constraint=models.UniqueConstraint(fields=('project', 'participant'), name='unique_project_participant'),
        ),
    ]
